import puppeteer from 'puppeteer';
const browser = await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless:'new', args:['--no-sandbox']});
const page = await browser.newPage();
await page.setViewport({width:1988,height:900,deviceScaleFactor:1});
await page.goto('http://localhost:4173/', {waitUntil:'networkidle2', timeout:60000});
await page.evaluate(()=>new Promise(r=>setTimeout(r,2500)));
const el = await page.$('.fusion-builder-row-11');
await el.scrollIntoView();
await page.evaluate(()=>new Promise(r=>setTimeout(r,400)));
const box = await el.boundingBox();
console.log('element box', box);
await el.screenshot({path:'_row11.png'});
await browser.close();
console.log('saved _row11.png');
