import fs from 'node:fs'

// Builds app/components/layout/SiteHeader.vue from the extracted Avada header DOM.
const full = fs.readFileSync('artifacts/header-full.html', 'utf8')
const short = fs.readFileSync('artifacts/header-short.html', 'utf8')

const navHrefs = [...new Set([...full.matchAll(/<a[^>]*href="(\/[^"]*|[^"]*\/)"/g)].map(m => m[1]))]

const lines = []
lines.push('<script setup lang="ts">')
lines.push("// SiteHeader: reusable Avada header (full = mega+phone, short = home).")
lines.push("// The current nav item is highlighted by matching the active route.")
lines.push("import { useRoute } from 'vue-router'")
lines.push("")
lines.push("withDefaults(defineProps<{ variant?: 'full' | 'short' }>(), { variant: 'full' })")
lines.push("const route = useRoute()")
lines.push("")
lines.push("function highlightCurrent() {")
lines.push("  if (typeof window === 'undefined') return")
lines.push("  const path = route.path.split('?')[0].replace(/\\/+$/, '')")
lines.push("  const cur = path === '' ? '/' : path")
lines.push("  document.querySelectorAll('.awb-menu__main-a[href]').forEach((a) => {")
lines.push("    // Only highlight items in the site navigation menus; leave the cart/search")
lines.push("    // widget menus (which Avada marks active itself) untouched.")
lines.push("    const scope = a.closest('#menu-vegan-store-main-menu, #menu-categories-mega-menu')")
lines.push("    if (!scope) return")
lines.push("    const href = a.getAttribute('href')")
lines.push("    if (!href || href.startsWith('http') || href === '#') return")
lines.push("    let h = href.split('?')[0].replace(/\\/+$/, '')")
lines.push("    if (h === '') h = '/'")
lines.push("    const isMatch = cur === h")
lines.push("    const li = a.closest('li')")
lines.push("    if (li) {")
lines.push("      if (isMatch) {")
lines.push("        li.classList.add('current-menu-item', 'current_page_item', 'awb-menu__main-li_active')")
lines.push("        a.setAttribute('aria-current', 'page')")
lines.push("      } else {")
lines.push("        li.classList.remove('current-menu-item', 'current_page_item', 'awb-menu__main-li_active')")
lines.push("        a.removeAttribute('aria-current')")
lines.push("      }")
lines.push("    }")
lines.push("  })")
lines.push("}")
lines.push("")
lines.push("onMounted(highlightCurrent)")
lines.push("watch(() => route.path, highlightCurrent)")
lines.push('</script>')
lines.push('')
lines.push('<template>')
lines.push('  <template v-if="variant === \'short\'">' + short + '</template>')
lines.push('  <template v-else>' + full + '</template>')
lines.push('</template>')

fs.writeFileSync('app/components/layout/SiteHeader.vue', lines.join('\n'))
console.log('SiteHeader.vue written,', lines.join('\n').length, 'bytes')
